### ISSUE TITLE
Elevating Prompt Quality for Desired Output

### ISSUE THREAD

**Issue by Gyan172004** [rootCircle/symmetrical-octo-spork#21]
Hello, Everyone!

We've noticed that prompts designed for answers might include unnecessary text that needs fixing. This issue requires attention to ensure cleaner prompts and accurate responses.

**Priority Question Types**: Multiple Choice Grid, Checkbox Grid.

I've attached screenshots showcasing the problem. While I'll be working on this, I welcome anyone interested to join the effort. Your contributions are highly valued.

It is also observed that same prompt gives different output sometimes so we need efficient prompts so that Engine give same and correct output everytime

<img width="360" alt="image" src="https://github.com/rootCircle/symmetrical-octo-spork/assets/137227305/01939c2f-eabe-48df-ae83-37164f383491">

<img width="424" alt="image" src="https://github.com/rootCircle/symmetrical-octo-spork/assets/137227305/24310197-05a4-4263-8529-9ea2f8592e55">

**Comment by rootCircle** [comment]
I am currently assigning this issue to you, unless someone else comes up! I also have done some testing and have seen the same issue with `MULTI_CORRECT_WITH_OTHER` type question, You can check that too.

**Comment by rootCircle** [comment]
Closing this as inactive!
