### ISSUE TITLE
Change of license to more premissive licenses like GPL or MIT

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/symmetrical-octo-spork#27]
Dear all,

It has been a long time since we started working on the docFiller extension. Although the intended result was noteworthy, the process was not without its challenges. Throughout this journey, we have seen contributors dedicating their time and effort to the project tirelessly. We have evolved from just an idea to a fully-fledged team, with a community manager, leads, comprehensive testing teams, a specialized development team, and more.

Now, the time has come for us to transition from a more restrictive license to a permissive license, in order to allow for potential future open source contributions. I would like to hear your opinions and request your approval in shaping the future of docFiller.

Thank you for your continued support and dedication.

Sincerely,
@rootCircle 

cc: @dev-KS-155 @Gyan-17 @ecxtacy @Harshit-Chordiya @Kota-Karthik @monarxxjain  @real-Vansh-Khare @Gyan172004

**Comment by ecxtacy** [comment]
Since we are going to engage more developers into contribution and for a general purpose usage, I'm in favor of the licence.

**Comment by EgressKS** [comment]
Yes, I support moving to a permissive licence.

**Comment by Kota-Karthik** [comment]
cool, I agree with it

**Comment by monarxxjain** [comment]
Absolutely, I fully support open sourcing the docFiller code. This will undoubtedly foster collaboration and innovation within our community. Great initiative!

**Comment by Harshit-Chordiya** [comment]
Yes, I agree.

**Comment by Gyan172004** [comment]
I support making DocFiller open source; it'll allow more folks to join in and improve it collectively.

**Comment by real-Vansh-Khare** [comment]
Yes, I support the move. This is the perfect time to switch to a permissive license.

**Comment by rootCircle** [comment]
Thanks everyone for your warm responses, this decision will truly will be a gamechanger for docFiller in my opinion, let's see what world has to offer!

Upon much research, I think 'GNU GPL 3.0 or later' might be best suited for our project. 
An upcoming commit will change the license for this repo that will hence affect and apply to but not  limited to all the past works and derivatives.
Thanks again!

**Comment by rootCircle** [comment]
[cfecdf8](https://github.com/rootCircle/docFiller/commit/cfecdf8e2ed4fbffce7a21afa1590475c2ca0dd2).
Change is live! Closing this for now!
