### ISSUE TITLE
[Feature]: UI Enhancements for Web Extension Options

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/symmetrical-octo-spork#38]
### Description

I propose adding a new UI for the web extension that will provide users with comprehensive settings for customizing their LLM usage. 

**Proposed Features:**

1. **Settings UI**:
   - **Default LLM**: Allow users to select a default LLM.
   - **API Key**: Provide a field for users to enter their API key.
   - **LLM Selection**: Enable users to choose which LLMs to use.
   - **Consensus Option**: Include a toggle to enable or disable the consensus-based response verification.
     - **Consensus Configuration**: If enabled, allow users to:
       - **Drag-and-Drop Order**: Specify the order of LLMs to be used.
       - **Weight Input**: Input the weight for each LLM as a percentage.

2. **Popup Page**:
   - Add a small enable/disable button to the popup page that provides quick access to enable or disable the consensus feature.

This enhancement will offer users greater control over their LLM settings and improve the overall flexibility of the web extension.

### Suggested Solution

**Implementation Details:**
- **Code Location**:
  - **UI Elements**: `src/option`, `src/popup` for TypeScript logic.
  - **HTML/CSS**: `public/option`, `src/popup` for HTML and CSS. (option is global UI and popup is session specific)
- **Functionality**:
  - Implement settings management to handle user inputs and configuration changes.
  - Ensure the consensus option is reflected accurately in the extension's behavior based on user preferences.
  - Make integrations with `chrome` WebExtension API as well!

**Comment by Gyan172004** [comment]
Fields like Name , email , `custom info` should be custom filled by user as well
