### ISSUE TITLE
Dynamic manifest.json based on browser type

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/symmetrical-octo-spork#70]
docFiller from start was being developed as Firefox first extension! But since introduction of ChromeAI and hence offline usage, we felt the need to have a development/build/package setup for chrome as well! 

docFiller uses content_scripts(Gecko)/service workers(Chromium). But it errors out when installed on Chromium based browser on non-development mode due to presence of content_scripts!

This is generally painful while packaging and testing for chromium based browser.

We propose a dynamic manifest.json that can emit manifest based on context provided (eg: `bun dev:firefox` for Gecko builds and `bun dev:chromium` for Chromium based builds)

cc: @Gyan172004

**Comment by Gyan172004** [comment]
I would like to implement a dynamic manifest.json to handle both Gecko (Firefox) and Chromium builds (Chrome, Edge) based on the context (e.g., bun dev:firefox for Firefox and bun dev:chromium for Chromium). This approach should resolve the issues with content_scripts in Chromium.
Mainly users have Gecko-based , Chromium-based and WebKit based browsers

We haven’t tested Safari (WebKit) yet — should I include Safari-specific handling in the dynamic manifest as well for full cross-browser compatibility?

**Comment by rootCircle** [comment]
Safari isn't the supported platform, and we don't have plans in any near future to distribute to Safari/WebKit based browsers.

But if can test it out, then PRs are always welcome! If not, we can leave it for later

ps: we also need to change scripts like `bun build` to `bun build:chromium` (& similar for firefox) and same for `bun pacakge` as well!

**Comment by Gyan172004** [comment]
I think I can make this work by creating a base `manifest.json` with common settings (like permissions, icons, and basic info). Then, for Firefox and Chromium, I can have separate browser-specific manifests that override the base ones. Based on which browser is targeted, the right settings will be applied. This approach should do the job?

**Comment by rootCircle** [comment]
I personally prefer this design(keeps all things at one place): https://github.com/antfu-collective/vitesse-webext/blob/main/src%2Fmanifest.ts 

Generator: https://github.com/antfu-collective/vitesse-webext/blob/main/scripts%2Fmanifest.ts

(but I am open to discussion)

**Comment by Gyan172004** [comment]
I think implementing everything in one place would be better. Overriding might introduce some issues down the line, so keeping it centralized seems more reliable.
