### ISSUE TITLE
Fix popup responsiveness for mobile devices

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/symmetrical-octo-spork#74]
We do provide Firefox Android as a supported platform. But, popup page is not responsive on mobile devices.

We need to fix this!

**Comment by Thunder-Blaze** [comment]
Sir can you assign this to me, I'll try to finish in 1-2 days :)

**Comment by rootCircle** [comment]
Sure go ahead, do it at your leisure and speed!

**Comment by Thunder-Blaze** [comment]
I changed some code
but I have no idea how to test it on phone ?

**Comment by Thunder-Blaze** [comment]
oh got it
got the tip from the latest issue
