### ISSUE TITLE
Privacy policy is not clickable in popup

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/symmetrical-octo-spork#75]
Due to overlay of toast-container onto the text spaning privacy policy in popup page, we can't click them.

One can manually open popup page in separate tab and decrease height below a threshold to see the effect!

**Comment by Thunder-Blaze** [comment]
Any case which will make the toast window appear ?
have made privacy policy and terms clickable, just wanna make sure toasts are working or not

**Comment by rootCircle** [comment]
Disable the extension and then click on fill button! That should do
